#+DATE: <2017-11-14 Tu>

* Meeting attendees

- Ahmadreza
- Michael
- Alex
- Chris
- William

* Agenda
** Member system

Michael talkes to Fortnox.
Also for accountant software.

** Bank account

Michael will mail Swedbank.
Swish.

Scheduled for <2017-11-13 Mo>--<2017-11-19 So>.

** Stora IT-kompetensdagen

Michael talks to Diana.
Lunch lectures

This companies will be at Stora IT-kompetensdagen and it would be nice if we could have lunch seminars with them before.

- Tecnau
- Gears of leo
- Infomaker Scandinavia
- Fortnox
- Visma
- Play'n Go
- IST
- Cybercom Sweden

 Ask diana about wexnet, griffel and other ISP (hardware companies)

*** NEW updates

18 companies need to spread the word to everyone we know :)

*** 2017-10-10 updates.

15-20 companies will be attending this year.

No lunch lectures planned yet.

*** 2017-10-12 updates

 9/11 play'n'go and CGI lunch lecture

Events are done. Everything went well.

*** 2017-11-14 updates

KK has a spot somewhere.

Known attendees:
- Marcus
- Michael
- Ahmadreza
- Alex
- Chris

We will stand around and talk to people. It is not must to stay at the stand.
** Global Entrepreneurship Week Dayhack

Cancelled

** Design

Ahmadreza

front end logos and stuff

Chris knows this. Needs to be fixed soon.

** Videum VR

Videum VR has a projectleader. Paul maybe as kodkollektivet contact??
first event someware after exams, end of october early november.
Johan updates Stefan at videum.

*** Update 2017-11-14

Ask Johan Leitet about streaming youtube.

** Hardware event

Chris has sent out emails.
Austin updates, DataCenter in älmhult.

*** 2017-10-10 updates

Michael Should mail Jakob in kalmar.
No updates.

*** 2017-10-10 updates

Chris creates a poll. Take best time from the voting.

Have the event during daytime. Even if there are possible conflicts.

** Hoodies

 No update.

*** 2017-10-10 updates.

No update.

*** 2017-11-14 updates

SVG is done. Graphics need some enhancements.

Chris puts the files onto Slack. Ask Chris if you have someone to fix it quickly.

** "Meet the kodkollektivet event"

   check with stallarna about cost and time?
   consoles?
   pizza?
   drinking games
   biljettkiosken 50 ppl max?
   workers?
   date?

*** 2017-10-10 updates

Move this event to november.
Marcus and Julia will lead the event from now

** CodeHub

New speakers?

- John? :: Emacs? 31/10? maybe IST as sponsor

*** 2017-11-14 updates

Ahmadreza spreads the news, that he is the head of codehub orga now. He will ask for new speakers. He also fixes the upcoming event.

Talks/Presentations need to be reviewed in advance. People need to send us the slides.

** Kodkollektivet server

John fixed a server with sigma.

Admin group for the server concept consists of
- John
- Chris

** Möte med Zenta

 2017-10-03

 Aida, Rasmus, Patrik, John

 1. Lunchföreläsning, datum?
    Återkom med datum til Aida.
    aidaqueenofthenorth@zenta.se

    No thursdays.
    16 November is Stora IT-kompetensdagen.

 2. Kvällsevent, Industri 4.0

 MakerSpace blir först om ett halvår?

*** 2017-10-10 updates.

    Patrik is working on getting a date for the lunch lecture. No date is set.
    The days they can choose from are 1 Nov and 8 Nov.
*** 2017-11-14 updates

Clarify that we need English presentations with the companies.

Event at Zenta is ongoing. KK will meet them and do stuff at their Makerspace. Loosely schedule for December.

** Meetings

We wanna have board meetings each second week. We think its better to have it on the same day as we have the CodeHub.

** Sigma event

Sigma event was very good. Looking forward to have more events in the future.

Kalmar guys liked it as well.

** Ongoing events

Michael is in contact with companies. Maybe more events in December.

** Future events

Advertise on FB and Slack that people/members can make suggestions for events and companies which we can meet.

** Spik Hackathon with Infomaker in Kalmar

Awesome event. Food, drinks, everyone was happy.

William mentioned that Infomaker wants to meet KK. They invite us to have a hackathon in Kalmar with them.

John knows hackathon location to ask for in Växjö. Infomaker is willing to come to Vaxjö as well to have a hackathon.

30-50 people attend KK Hackathons in average.

** General event management and PR

30-50 people attend KK Hackathons in average.

William mentions that having the events in Växjö in general would be a good idea.

Flyer/Info what KK does, how many we are, what we do with the companies and so on. William will fix this and updates information on the website. Will be fixed until the weekend before next board meeting (<2017-11-26 Su>)

** Media responsible

Advertise more on FB and other media in general.

Take at least photos with smartphones on events. Bigger events should be documented with decent cameras.

Media responsible pokes and asks around that we take pictures.
Alex and Chris are responsible for now.

Goal is to have better PR and overview about past events.
