#+TITLE: Kodkollektivet stadgar
#+AUTHOR: Kodkollektivet
#+OPTIONS: toc:nil num:nil date:nil author:nil


* §1.1 Namn

  Föreningens namn är Kodkollektivet. Nedan kallas "Föreningen".

* §1.2 Säte

  Föreningens säte är Växjö.

* §1.3 Syfte

  Föreningens syfte är att främja och inspirera intresset för programmering,
  mjukvaruutveckling, säkerhet och relaterade ämnen för studenter inom Linnéuniversitetet.

* §1.4 Oberoende och organisation

  Föreningen drivs ideellt, är partipolitiskt och religöst oberoende. Föreningens åsikter
  och ställningstaganden är inte heller representativa för föreningens samarbetspartners
  eller vise versa.

* §1.5 Upplösning

  För upplösning av föreningen krävs godkännande av minst 90% majoritet av de röstande på
  nästkommande stormöte. Vid upplösning ska, efter att eventuella skulder betalats,
  kvarvarande likvida medel tillfalla en ideell organisation vald av föreningens
  medlemmar.

* §2.1 Medlemskap

  En person äger rätt till medlemskap så länge hen är registrerad som student
  vid Linnéuniversitetet och betalt medlemskap för terminen.

* §2.2 Medlemsavgift

  Medlemsavgift erlägs av föreneningens nyvarande styrelse på föreningens Stormöte §3.2.

* §2.3 Medlemmar

  Medlemskap erhålls för en termin genom inskrivning i medlemsregistret och betalning av fastställd medlemsavgift.

* §2.3.1 Undantag

  Sittande styrelsemedlemmar samt revisorn betalar ingen medlemsavgift men är ändå
  medlemmar i föreningen.

* §2.4 Uteslutande av medlem

  Styrelsen kan lägga fram en proposition om att utesluta en medlem om denne har motarbetat färenings arbete, skadat föreningens verksamhet eller anseende. Beslut om uteslutan bestäms på nästkommande stormöte genom två tredjedelars majoritet av stormötets närvarande medlemmar.

* §3.1 Verksamhetsår

  Föreningens verksamhetsår sträcker sig mellan 1 September till och med 31 Augusti
  nästföljande kalenderår.

* §3.2 Stormöte

  Ett stormöte är föreningens högsta beslutande organ där samtliga medlemmar har rösträtt. En kallelse till stormöte, samt en preliminär föredragningslista §3.2.1, anslås på föreningens hemsida minst två (2) veckor innan utsatt datum.

* §3.2.1 Föredragningslista

  Den slutgiltiga föredragningslistan måste anslås på föreningens hemsida senast en (1)
  vecka innan utsatt datum för stormötet. Efter detta får föredragningslistan ej ändras
  innan mötet. Varje föredragningslista måste innehålla minst följande punkter:

  - Val av mötesordförande
  - Val av mötessekreterare
  - Val av justeringsperson tillika rösträknare
  - Fastställande av röstlängden
  - Beslut om mötets stadgeenliga utlysande
  - Motioner och propositioner
  - Övriga frågor

* §3.2.2 Motioner

  Motioner måste skickas in skriftligen till den sittande styrelsen senast två (2) veckor
  innan utsatt datum för ett stormöte. De blir sedan en del av den slutgiltiga
  föredragningslistan tillsammans med ett motionssvar från den sittande styrelsen.

* §3.2.3 Beslut

  Beslut fattas med enkel majoritet. Röstning med fullmakt får ej förekomma. Medlemmar
  kan begära votering. Vid lika röstetal har föreningens ordförande utslagsröst. För att föra in ett nytt ärende på föredragningslistan erfordras 75% majoritet. Under punkten
  “övriga frågor” får det ej behandlas frågor som gäller kostnader.

* §3.2.4 Adjungeringar

  Stormötet kan adjungera personer. Med adjungering avses närvaro-, yttrande- och
  förslagsrätt. Adjungering medför ej rätt att deltaga i beslut, ej heller medansvar för
  fattade beslut.

* §3.2.5 Protokoll

  Stormöten måste protokollföras. Dessa skall anslås på föreningens hemsida och skall arkiveras. Protokoll ska vara färdigställda inom fyra (4) veckor efter ett möte.

* §3.2.6 Justering av protokoll

  Protokoll från stormöte skall justeras av mötesordföranden, mötessekreteraren och en av
  mötet utsedd justeringsperson.

* §3.3 Terminsmöte

  På våren samt hösten varje verksamhetsår skall ett stormöte hållas. Detta kallas
  terminsmötet. Terminsmötets föredragningslista måste, förutom de som nämns i §3.2.1,
  minst lyfta punkterna:

  - Fastställandet av nästa verksamhetsårs medlemsavgift
  - Val av nästföljande verksamhetsårs styrelse
  - Val av nästföljande verksamhetsårs revisor
  - Fastställande av nästkommande verksamhetsårs budget
  - Föregående verksamhetsårs styrelses verksamhetsberättelse
  - Föregående verksamhetsårs styrelses ekonomiska berättelse
  - Revisorns granskning av föregående verksamhetsårs styrelses arbete
  - Beslut om ansvarsfrihet av föregående verksamhetsårs styrelse

* §3.3.1 Extra stormöte

  Vid behov kan ett extra stormöte sammankallas av 50% av styrelseledamöterna. Vid yrkande om extra stormöte skall en kallelseu fastslås inom två (2) veckor.

* §3.4 Styrdokument

  Föreningens verksamhet regleras av dessa stadgar. För att ändra i stadgarna krävs 75% majoritet på ett stormöte.

* §3.4.1 Tolkingsfrågor

  Om tolkningsfrågor skulle uppstå i styrdokumenten gäller styrelsens mening, tills
  frågan avgjorts på stormöte. Efter avklarad tolkningsfråga skall formuleringen som gav
  upphov till situationen justeras enligt stormötets beslut.

* §3.5 Entledigande

  Då särskilda skäl färeligger kan styrelsen efter skriftlig ansökan från styrelsemedlem
  entlediga vederbörande samt tillförordna annan person att fullgöra den entledigades
  uppgifter till nästa stormöte, då val skall ske. Styrelsen äger ej rätt att entlediga:

  - Ordförande
  - Kassör
  - Revisor

* §4 Styrelsen

  Styrelsen handhar ledning av föreningens verksamhet i enlighet med syftet, se §1.3,
  under verksamhetsåret. Styrelsen består minst av följande ordinarie ledamöter:

  - Ordförande
  - Vice Ordförande
  - Kassör
  - Revisor
  - Interna Relationer
  - Externa Relationer
  - Styrelserådgivare

* §4.1 Rättigheter och skyldigheter

  Det åligger styrelsen att:

  - Besluta om den löpande verksamheten
  - Bereda ärenden, vilka skall behandlas vid stormöten
  - Upprätta förslag till föredragningslista för stormöten
  - Inför stormöten ansvara för föreningens verksamhet
  - Verkställa av stormöten fattade beslut
  - Förbereda sina efterträdare inför deras verksamhetsår

* §4.2 Styrelsemöten

  Styrelsemöten måste hållas minst en gång per termin under verksamhetsåret.
  Styrelsemöten är beslutsmässiga då minst hälften av ledamöterna är närvarande.

* §4.2.1 Adjungeringar

  Styrelsemötena likt stormötena kan adjungera personer, se §3.2.7

* §4.3 Protokoll

  Styrelsemöten måste protokollföras. Dessa skall anslås på föreningens hemsida och skall arkiveras. Protokoll ska vara färdigställda inom fyra (4) veckor efter ett möte.

* §4.4 Firmateckning

  Föreningens firma, om sådan finns, tecknas av Ordföranden och Kassören var för sig.

* §5 Revision

  En revisor skall väljas på terminsmötet som ska granska föreningens verksamhet.
  Revisorn ska agera både sak- och sifferrevisor. Revisorn skall vara myndig och får ej
  vara jävig.

* §5.1 Åligganden

  Revisorn skall före terminsmötet avsluta sin granskning av föregående termins
  verksamhet och över den företagna revisionen upprätta revisionsberättelse.

* §5.2 Handlingar

  Räkenskaper och övriga handlingar skall tillställas revisorn löpande fram til terminsmötet.

* §5.3 Rättigheter

  Revisorn har rätt att närvara vid styrelsemötena. Revisorn skall ha insikt till
  föreningens tillgångar. Revisorn kan anmoda förtroendevalda att lämna ut information
  som behövs för en korrekt revision.
