#+TITLE: Kodkollektivet Projects

* Calendar

Nginx proxy for read only access

#+BEGIN_SRC
server {
    location /iCalendar/export {
        proxy_pass http://localhost/baikal/html/cal.php/calendars/{USERNAME}/default?export;
        proxy_set_header Authorization "Basic dXNlcm5hbWU6cGFzc3dvcmQ=";
    }
}
#+END_SRC

** Letsencrypt

uberspace-letsencrypt

letsencrypt certonly

 uberspace-add-certificate -k ~/.config/letsencrypt/live/dav.kodkollektivet.se/privkey.pem -c ~/.config/letsencrypt/live/dav.kodkollektivet.se/cert.pem


** Baikal

http://sabre.io/baikal/install/

Download newest release from
https://github.com/fruux/Baikal/releases

Release in this doc: 0.4.6

E.g. ssh into remote server and hit
#+BEGIN_SRC sh
cd /var/www/virtual/kodkoll/projects
wget https://github.com/fruux/Baikal/releases/download/0.4.6/baikal-0.4.6.zip
#+END_SRC

Unzip
#+BEGIN_SRC sh
unzip baikal-0.4.6.zip
#+END_SRC

Link installation to domain
#+BEGIN_SRC sh
ln -s /var/www/virtual/kodkoll/project/baikal/html dav.kodkollektivet.se
#+END_SRC

Go to url with your browser: http://dav.kodkollektivet.se

Select proper time zone and choose *Digest* method for auth:

Digest Authentication communicates credentials in an encrypted form by applying a hash function to the the username, the password, a server supplied nonce value, the HTTP method, and the requested URI.

Setup baikal with strong password.

Modify baikal/html/.htaccess to force https

#+BEGIN_SRC
<IfModule mod_rewrite.c>
    RewriteEngine On
    #RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
    RewriteCond %{HTTPS} !=on
    RewriteCond %{ENV:HTTPS} !=on
    RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
</IfModule>
#+END_SRC

Patch file Specific/config.system.php

#+BEGIN_SRC
# Should begin and end with a "/"
define("BAIKAL_CARD_BASEURI", "/" . "card.php/");

# Should begin and end with a "/"
define("BAIKAL_CAL_BASEURI", "/" . "cal.php/");

# Should begin and end with a "/"
define("BAIKAL_DAV_BASEURI", "/" . "dav.php/");
#+END_SRC

The base url, which is something like http://example.org/caldav/calendarserver.php/.
The principal url, which is something like http://example.org/caldav/calendarserver.php/principals/admin/.
The calendar url, which is something like http://example.org/caldav/calendarserver.php/calendars/admin/default/.


** Fennel on Uberspace (not working bc of glibc)

*** Installation

#+BEGIN_SRC
cd projects
git clone https://github.com/LordEidi/fennel.git
cd fennel
npm install
#+END_SRC

*** Authentication

htaccess is used to authenticate the user. Please check the [[https://github.com/LordEidi/fennel][project's website on github]] for any other authentication methods.

apache's apr password format is used to save the password hash. Read more about apache's password formats here: https://httpd.apache.org/docs/2.2/misc/password_encryptions.html

Example user.htaccess file:
#+BEGIN_EXAMPLE
username:$apr1$qHDFfhPC$nITSVHgYbDAK1Y0acGRnY0
#+END_EXAMPLE

Hash password for the htaccess format. Never use an online service to create a new password hash – you can't trust them. instead, use your trusted command prompt:

#+BEGIN_SRC
openssl passwd -apr1
#+END_SRC

*** Port setup

Open port for your system. On uberspace:
#+BEGIN_SRC
uberspace-add-port -f -p tcp
#+END_SRC

*** Configuration

Change /config.js/ accordingly

#+BEGIN_EXAMPLE
port: <accessible_port>
[…]
auth_method_htaccess_file: '/home/kodkoll/projects/fennel/user.htaccess',
[…]
db_storage: '/home/kodkoll/projects/fennel/fennel.sqlite',
#+END_EXAMPLE

Run the server! On uberspace:
#+BEGIN_SRC
uberspace-setup-service fennel node ~/projects/fennel/server.js
#+END_SRC

Access server through subdomain

On uberspace do
#+BEGIN_SRC
mkdir /var/www/virtual/kodkoll/dav.kodkollektivet.se
#+END_SRC

Setup /.htaccess/ file in subdomain
#+BEGIN_SRC
vim /var/www/virtual/kodkoll/dav.kodkollektivet.se/.htaccess
#+END_SRC

Add the following content and set port according to your port configuration:
#+BEGIN_EXAMPLE
RewriteEngine on
RewriteRule (.*) http://localhost:<accessible_port>/$1 [P]
#+END_EXAMPLE

*** Service control on uberspace

To control your service on uberspace you'll need the svc command (hint: svc = service control):

To start the service (hint: u = up):
#+BEGIN_SRC
svc -u ~/service/fennel
#+END_SRC

To stop the service (hint: d = down):
#+BEGIN_SRC
svc -d ~/service/fennel
#+END_SRC

To reload the service (hint: h = HUP):
#+BEGIN_SRC
svc -h ~/service/fennel
#+END_SRC

To restart the service (hint: du = down, up):
#+BEGIN_SRC
svc -du ~/service/fennel
#+END_SRC

To remove the service:
#+BEGIN_SRC
cd ~/service/fennel
rm ~/service/fennel
svc -dx . log
rm -rf ~/etc/run-fennel
#+END_SRC
* Unitime-js

** unitime api call
#+TITLE: Meeting notes for infrastructure plannin
#+DATE: <2018-10-10 Wed>

* Infrastructure
** Uberspace
- Shared hosting platform
- Main maintenance is done by the uberspace team
- 10 GB uberspace instance
- Donation based 5-6 € / month
- Uberspace U7 is available in English / English documentation

Current services running
- Handles mail boxes and reception of mails

** Self hosted server @sigma
- 30 GB storage
- 15 GB RAM
- Debian 9
- Runs website
- Server is sponsored by Sigma ITC

The server is running the following projects:
- https://github.com/Kodkollektivet/kodkollektivet.se

** Domain

- John has the domain registered in his own account
- John wants to transfer this domain to another domain registry
- Kodkollektivet should register an account
  - Kodkollektivet organization should open an account and initiate the domain transfer
  - Students are "only" here for ~3 years, so it should be directly connected to the organization

Use binero to register the domain
https://www.binero.se/
** Services
*** Main services

- Domain: 119 SEK / year
- Website: free @sigma server
- Mail: 5-6 € / month, maybe move to binero or something else
- Communication, slack free but causes problems due to information loss (10.000 messages)
  - Alternatives
    - riot.im
    - rocket.chat
- Nextcloud
  - Media storage, Calendar, Contacts, Mail client
  - We try it and see if it works for us
- Project Management
  - Nextcloud Kanban / Scrum addon
  - taigo.io
- Realtime collaboration
  - Nextcloud LibreOffice?
  - Etherpad lite

*** Interesting services

- GitLab
- Hastebin
