DATE: <2017-02-28 Tue 16:00-17:00>

* Positions for this meeting:

  - President: Rasmus Sjostrom
  - Secretary: Johan Rovala
  - Adjustor: John Herrlin

* Attendants:

 - Vahida Ahmic
 - Abdi Ahmed
 - Alex Spottka
 - Austin Pontén
 - Rasmus Sjöström
 - Otto Bergman
 - Hatem Houssein
 - Johan Rovala
 - John Herrlin

* Agenda:

** Gymnasiedagarna 16/3

Närvarande för gymnasiedagarna samt storlek för tröja:
- Alex Spottka M Svart
- Otto Bergman M Svart
- Hatem Houssein S Svart
- Rasmus Sjöström M Svart
- Vahida Ahmic XS (girl, minsta) Svart
- John Herrlin S Svart
- Austin Pontén M Svart

The money recieved will go to kodkollektivet, this was decided by a unanimous vote.

** Marketing our school

Hatem has suggested that we market our programs to different schools in the local region.
As a result we should be accommodated for it by LNU.

** Shaping the education

Johan suggests that we discuss with companies what they wish LNU had in their education
plan.

** Team building

Suggestions for team building has been brought up. Majority vote settled on Boda
Borg. John will talk to Visma about sponsorship for this event.
