DATE: <2017-10-03 Tue 18:00>


* Agenda
** Member system

    Michael talkes to Fortnox.
    Also for accountant software.


** Bank account

    John will mail Swedbank.
    Swish.

** Stora IT-kompetensdagen

    Michael talks to Diana.
    Lunch lectures:

    This companies will be at Stora IT-kompetensdagen and it would be nice if we could have
    lunch seminars with them before.

    - Tecnau
    - Gears of leo
    - Infomaker Scandinavia
    - Fortnox
    - Visma
    - Play'n Go
    - IST
    - Cybercom Sweden

      Ask diana about wexnet, griffel and other ISP (hardware companies)

** Global Entrepreneurship Week Dayhack

    No update

    Dagshackathon.

    Global Entrepreneurship Week, 13-19 Nov Måndag - Söndag, vad sägs om Lördagen 18?

    Drivhuset är det som driver det.
    Videum är med på ett hörn med en nätverksträff.

    Kör det på biljettkiosken för anmälan, brandad med Kodkollektivet.

    Köra det under en dag:
    09:00 Start och into, enkel macka.
    12:00 Lunch
    17:00 Presentation
    18:00 Middag och dryck

    Få med någon ifrån kodkollektiv2et till en styrgrupp, Vahida?
    Vahida, kolla med EBD. Erik Rosell kan vara bra.
    Fixa studenter som är sugna.
    Tanken är att bygga grupper på 4 pers med 2 utvecklare och 2 EBDare.
    Sedan är det en panel som bestämmer.

    Vi räknar med ~20 studenter.

    Sätta ihop en panel där sponsor också kan få sitta med.

    !!!!UPDATE!!!!! 12/9 - 2017
    EHVS want payment for advertisments, maybe posters are better.
    Meeting again 13/9 -2017
    Problem for event something about some communityproblem.
    Chris is interested to join.
    Vahida should update Amar on this.

** Design

    Front end, logos and stuff

    Ahmadreza and Chriss takes care of it.

** CodeHub posters

   Michael, Fix general poster to leave up "Codehub varannan tisdag bla bla"
   Wait for next event to change room.
   Room key??
   Just a mail away.
   Limit the talks about to 20 minutes.

** Videum VR

   Videum VR.
   Johan will meet with Stefan and Viktor Karlsson.

   If someone is interested in this, talk to Johan Rovala!
   Michael will talk to students about this to!

** Social beer

   Meetup in town to drink a beer.
   <2017-09-12 Tue 20:00> somewhere in town.
   Alex creates the event.

   No update maybe start in october.

   Fridays 29/9-17 around 17:00?

** Hardware event

   Chris has sent out emails.
   Austin updates, DataCenter in Älmhult.

** Chris host

   This is done.
   Post the cridentials in Slack #board channel.

** Discord?

   What do we think about it?
   Should we keep it or Slack?

** Hoodies

    Alex checks if we can get vector graphics of logos. Else Otto converts it.
    Mellis sister trys to convert it.

    Ahmadreza and Chriss takes care of it.

** "Meet the kodkollektivet event"

    check with stallarna about cost and time?
    consoles?
    pizza?
    drinking games
    biljettkiosken 50 ppl max?
    workers?
    date?

    There is a Slack channel for that.

** CodeHub

   New speakers?
   - Chriss :: Imageprocessing (ImageMagick) 10/10 -17 Invite designers!
   - Ahmadreza :: React native 24/10 -17

** Möte med Zenta
   2017-10-03

   Aida, Rasmus, Patrik, John

   1. Lunchföreläsning, datum?
      Återkom med datum til Aida.
      aidaqueenofthenorth@zenta.se

      No thursdays.
      16 November is Stora IT-kompetensdagen.

   2. Kvällsevent, Industri 4.0

   MakerSpace blir först om ett halvår?
** Teknikum

   Go and talk to students.
   - John Herrlin, SV
   - Ahmadreza, EN

   4 hours, 14 Oktober.
