* Meeting attendees

- Marcus
- Michael
- Tomas
- Vahida
- Anni

* Agenda
** Member system
Talking with Fortnox so on the way.

update 24/4
fortnox account has been created, and can currently be used by Vahida and Michael.

------------------------------------------------------------------------

** Bank and money
biljettkiosken for each event.
Invoice to LNU is sent.

Update 24/4
------------------------------------------------------------------------
not accounted. 10000 going to codehub fika etc. accounting done on wednesday

** Kodkollektivet goes Deluxe
| Domain        | Responsible people       |
|---------------+--------------------------|
| Snacks        | Chris                    |
| Prices        | Michael, Alex            |
| Companies     | Ahmadreza, Michael, Alex |
| Poster/FB     | Julia, Ahmadreza         |
| Messageboard  | Julia                    |
| Quiz          | Alex, Chris, Marcus      |
| Game          | John, Alex               |
| Proudest Geek | Marcus, Julia            |
| Group game    | Chris                    |
| Music         | Chris                    |

Update 27/3
------------------------------------------------------------------------
Design of Facebook.
Julia handles the Facebook event.
Deadline friday 30 mars for the facebook event.
Invite södra with Chris and julias report.
Advertise on facebook.
biljettkiosken, 50 kr a ticket.
Marcus writes about proudest geek.
Julia thinks about group games. Chris does thesis.

Update 24/4
------------------------------------------------------------------------

** CodeHub.
- Michael will supply food and drinks for codehub
- Marcus will provide the knives and cutting boards
- Board prepares food before the codehub

Update 27/3
------------------------------------------------------------------------
Amadreza not on meeting.
Security event next time? Tomas might have a talk.

Update 24/4
------------------------------------------------------------------------
chill codehub today.
last codehub 8 may. Doing thesis introductions

** Board dinner
wednesday 2/5 18:30 everyone should contact michael if they can or not.

** Annie talks about the Linnestudenterna board
We will make a post and endorse annie in the vote.

** Party discussion
Good party
etc :D
positive.

Julia is fixing the images!
